[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.30"
egui_taffy = { path = ".." }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
web-sys = "0.3.76"
